services:
  - type: web
    name: ptc-election-system
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ptc-election-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: ptc-election-db
    plan: starter