name = "pp-ptc"
compatibility_date = "2025-09-03"
main = "workers/src/index.ts"

# Enable Node.js compatibility (needed for some Node packages)
compatibility_flags = ["nodejs_compat"]

# # KV namespace for session storage and caching
# [[kv_namespaces]]
# binding = "KV"
# id = "ptc_kv_namespace"
# preview_id = "ptc_kv_preview"

# # R2 bucket for file uploads
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "ptc-files"
# preview_bucket_name = "ptc-files-preview"

# # D1 database for SQLite
# [[d1_databases]]
# binding = "DB"
# database_name = "ptc-election-db"
# database_id = "your-d1-database-id"

# Environment variables for production
[vars]
NODE_ENV = "production"

# Note: For security, set these via Cloudflare dashboard or wrangler secrets:
# wrangler secret put SESSION_SECRET
# wrangler secret put DATABASE_URL  
# wrangler secret put ENCRYPTION_KEY

# [env.development.vars]
# NODE_ENV = "development"
# SESSION_SECRET = "dev-session-secret"
# DATABASE_URL = "postgresql://localhost:5432/ptc_election"
# ENCRYPTION_KEY = "dev-encryption-key-32chars-long"

# Build configuration - let Wrangler handle the TypeScript compilation
[build]
command = "npm run build"

# # Durable Objects for WebSocket support
# [[durable_objects.bindings]]
# name = "WEBSOCKET_DO"
# class_name = "WebSocketDurableObject"

# [[migrations]]
# tag = "v1"
# new_classes = ["WebSocketDurableObject"]

# # Limits and settings
# [limits]
# cpu_ms = 50
